### ISSUE TITLE
Failed to sync Gradle project

### ISSUE THREAD

**Issue by cgathergood** [forcedotcom/DeskMobileSDK-Android#40]
Following the provided instructions and including

```
repositories {
  jcenter()
}

dependencies {
  compile 'com.desk:sdk:1.2.0'
}
```

The Gradle build fails with the following error:

> Error:Could not find com.squareup.okhttp:okhttp-urlconnection:2.6.0-SNAPSHOT.
> Required by:
>     PROJECT_NAME:app:unspecified
>     PROJECT_NAME:unspecified > com.desk:sdk:1.2.0 > com.desk:api-client:1.2.0

I have tried to add the specific snapshot dependency but the error still persists.

**Comment by cgathergood** [comment]
Turns out this was conflicting with my current OKHTTP dependencies.
That and the min sdk was set to 15 (desk needs 16)

**Comment by jpike88** [comment]
how did you fix it exactly?

**Comment by cgathergood** [comment]
Hey @jpike88 , this issue was solved by removing duplicate OKHTTP dependencies (I was already using Retrofit) and setting my min SDK to 16

Ultimately I  did not end up using the provided SDK and sent support tickets via a standard POST request

**Comment by jpike88** [comment]
Yeah that sucks... now to give UserVoice a crack.
