### ISSUE TITLE
BROKEN: CAN'T INSTALL

### ISSUE THREAD

**Issue by jpike88** [forcedotcom/DeskMobileSDK-Android#46]
Error:A problem occurred configuring root project 'android'.

> A problem occurred configuring project ':blahblahblah'.
> Could not resolve all dependencies for configuration ':blahblahblah'.
>       > Could not find com.squareup.okhttp:okhttp-urlconnection:2.6.0-SNAPSHOT.
>         Searched in the following locations:
>             https://repo1.maven.org/maven2/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/maven-metadata.xml
>             http://repo1.maven.org/maven2/com/squareup/okhttp/okhttp-urlconnection/2.6.0/
>             https://repo1.maven.org/maven2/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.pom
>             https://repo1.maven.org/maven2/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.jar
>             https://jcenter.bintray.com/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/maven-metadata.xml
>             https://jcenter.bintray.com/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.pom
>             https://jcenter.bintray.com/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.jar
>             https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/maven-metadata.xml
>             https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.pom
>             https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp/okhttp-urlconnection/2.6.0-SNAPSHOT/okhttp-urlconnection-2.6.0-SNAPSHOT.jar

**Comment by jerrellmardis** [comment]
Fixed in #49
